### ISSUE TITLE
ExpressVpn_Monitor.service core dumps when started by systemd

### ISSUE THREAD

**Issue by chasbro-1** [MaherGebrail/ExpressVpn_Monitor_Status#1]
Linux Mint 21 - Cinnamon
User auto start is disabled.  systemctl --user is enabled.  On reboot ExpressVpn_Monitor.service core dumps.

systemctl --user status startExpressVpn_Monitor.service
× startExpressVpn_Monitor.service - ExpressVpn Monitoring
     Loaded: loaded (/home/********/.config/systemd/user/startExpressVpn_Monitor.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Wed 2022-08-24 10:39:57 CDT; 16s ago
    Process: 1884 ExecStart=/opt/Vpn_Monitor/ExpressVpn_Monitor.py (code=dumped, signal=SEGV)
   Main PID: 1884 (code=dumped, signal=SEGV)
        CPU: 89ms

Aug 24 10:39:57 i3793 systemd[1873]: Started ExpressVpn Monitoring.
Aug 24 10:39:57 i3793 python3[1884]: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Aug 24 10:39:57 i3793 python3[1884]: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)'>
Aug 24 10:39:57 i3793 python3[1884]: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)'>
Aug 24 10:39:57 i3793 python3[1884]: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)'>
Aug 24 10:39:57 i3793 systemd-coredump[1936]: Process 1884 (python3) of user 1000 dumped core.
                                              
                                              Found module linux-vdso.so.1 with build-id: 8e7072b0cec20aca667bf5f51bbb5be9a99a0bb9
                                              Found module libayatana-ido3-0.4.so.0 with build-id: 5c566735a98df1195f0e808e02aad965>
                                              Found module libdbusmenu-glib.so.4 with build-id: 849f1b8d83849e5e7c2a293746819d2c4dc>
                                              Found module libdbusmenu-gtk3.so.4 with build-id: 3465e63a411b5cd0d1f806b8a528cdc7293>
                                              Found module libayatana-indicator3.so.7 with build-id: baccc4c7985ae78c96334737403306>
                                              Found module libappindicator3.so.1 with build-id: 7ae8b25a15d2763df69f3f9d3696a41132b>
                                              Found module libnotify.so.4 with build-id: 9f17eb75ce0087dc0e9e2049eeb47d37883006e3
                                              Found module libgpg-error.so.0 with build-id: 3fbec71c67bee60d8aef00697ee187079b0fb307
                                              Found module libgcrypt.so.20 with build-id: 60a5e524de0ed8323edf33e9eb9127a9eee02359
                                              Found module libcap.so.2 with build-id: 9e11e3bca4b0a25d047cb36e933e1d727663cf8e
                                              Found module liblz4.so.1 with build-id: a85971851cd059f1af80d553c8e7170d42ec59a1
                                              Found module libzstd.so.1 with build-id: 5d9d0d946a3154a748e87e17af9d14764519237b
                                              Found module libsystemd.so.0 with build-id: 75231451ceb15e04815af96824efdfe87f3994f6
                                              Found module libatspi.so.0 with build-id: 2843c68233d5ba81da3d6bc31422e49472873dba
                                              Found module libdbus-1.so.3 with build-id: 24105ac5af0c61583cb7928d54701f31fd45ba5a
                                              Found module libatk-bridge-2.0.so.0 with build-id: 7e8009077fbdcd7bf094c51bf78742b96f>
                                              Found module libatk-1.0.so.0 with build-id: b93088667fbd06f6b72d273403d352e7c0554698
                                              Found module libgtk-3.so.0 with build-id: 9a340345f5e200f42140f3cb4bacb407e91843f8
                                              Found module libpangoft2-1.0.so.0 with build-id: a7dd79c7ea8ec4d5791f83f9a8f34ffbfa8c>
                                              Found module libepoxy.so.0 with build-id: 5ea53a2b100e4b044eee19d5222881a724abf046
                                              Found module libwayland-client.so.0 with build-id: 27ff56a6713b99a77040528f36371fec77>
                                              Found module libwayland-egl.so.1 with build-id: b3612433fb88e7d36f0e5ac97d264970646c4>
                                              Found module libwayland-cursor.so.0 with build-id: 7e0b223d28b0b0714153befc62cd3d4b03>
                                              Found module libxkbcommon.so.0 with build-id: a4b17d939092101dc8f6b2a1d70eaf1fddb2dd51
                                              Found module libXfixes.so.3 with build-id: a9c550a40b8154a3b4b5e2ac182bb50c013c3f18
                                              Found module libXdamage.so.1 with build-id: 8358b7625700dc247fa21fb4304cba877a28bb04
                                              Found module libXcomposite.so.1 with build-id: 2c84db5342304ba1a76db7dd9b7a3bfaa8a716>
                                              Found module libXcursor.so.1 with build-id: d936a5db46d8babb0f2cc490df36b6b18a16d8aa
                                              Found module libXrandr.so.2 with build-id: 069f930a2b41f3908a1a92b1a51c38bd13a559e2
                                              Found module libXi.so.6 with build-id: 8ff5a3ac871a90fd9d0a7917c61f748a41c6b5ee
                                              Found module libXinerama.so.1 with build-id: 9823bebfa26a681265db4aeb09abf44deec38401
                                              Found module libpangocairo-1.0.so.0 with build-id: cb231e62ccba07e561d1d08804e975f615>
                                              Found module libgdk-3.so.0 with build-id: 97b768ef80858a79741be2492754d948989e63c6
                                              Found module libjpeg.so.8 with build-id: c54abff9294357e28532a76a049a4cb2542fc15b
                                              Found module libgdk_pixbuf-2.0.so.0 with build-id: bf3b72807368bcb97042b13e9aafaab1c7>
                                              Found module libgraphite2.so.3 with build-id: 5ffbc76fc948f6b88d766a7210c2e6a329a6c278
                                              Found module libdatrie.so.1 with build-id: 128b6874a47f2b783d9e9060d3caaee4110bfd3d
                                              Found module libharfbuzz.so.0 with build-id: 3b9c495c079286b8d1f55d0937a0a771593eb7e6
                                              Found module libthai.so.0 with build-id: afa54530349e68380815d606d15dbfda8952799f
                                              Found module libfribidi.so.0 with build-id: 6e075a666e1da8ffdb948d734e75d82b1b6dc0fb
                                              Found module libpango-1.0.so.0 with build-id: 2d778a30dd59c0673b0208c538999ccc0991093a
                                              Found module _cairo.cpython-310-x86_64-linux-gnu.so with build-id: a4873ac2dc5e5d0791>
                                              Found module libmd.so.0 with build-id: cd2d2f71b3967ebde30e2aa43b8eb63339020c06
                                              Found module libbsd.so.0 with build-id: 9a6c72469251e2feb63e175ef5cb944ce6e00df3
                                              Found module libbrotlicommon.so.1 with build-id: 43a72967cf84155914c8b3e915926733d1e5>
                                              Found module libXdmcp.so.6 with build-id: 6b60f99504aa1d3999ea02a14366d1a39d6c5dcf
                                              Found module libXau.so.6 with build-id: 7089b383cacbfc1760634a3be19a923e51fe3315
                                              Found module libbrotlidec.so.1 with build-id: 4b1f390dd6e24d49684db8b2443d082379e8e977
                                              Found module libuuid.so.1 with build-id: 64c0d0cb22fa2bdeca075a0c0418ba5ff314b220
                                              Found module libXext.so.6 with build-id: 9fb1880e02dfa11a8c39cd1a170109de08302059
                                              Found module libX11.so.6 with build-id: b8d9314a7185312e4813abcac67d8b68ae2fd690
                                              Found module libXrender.so.1 with build-id: 7ccbfa4c24e93c42fa50dd2e42fa277630f9650c
                                              Found module libxcb-render.so.0 with build-id: cb521131fd3b0f2ee6056cbc2014b3b8ef0d5c>
                                              Found module libxcb.so.1 with build-id: 1bef862a339557aa16c34c7a4b27f8f3aea90517
                                              Found module libxcb-shm.so.0 with build-id: edb24ef4079aa423edcc50a3bb0dfb912fe8a57a
                                              Found module libpng16.so.16 with build-id: d58bf7c11ac793d528926238d831792b5ef792cf
                                              Found module libfreetype.so.6 with build-id: e3aff1d56fb1aecc723a73882f7d0f208a36c4bc
                                              Found module libfontconfig.so.1 with build-id: 0bb435fdd5ec37178e14ea03bb36f779a4b72a>
                                              Found module libpixman-1.so.0 with build-id: e24db0bd24ff8f8ce4efed29e30b8f3d35a1bfe6
                                              Found module libcairo-gobject.so.2 with build-id: 71b5bd37d77ea1862d2ed00e9f6ead482f3>
                                              Found module libcairo.so.2 with build-id: 60a39c3684e41370bd0a59ed1ecbdccf47e30069
                                              Found module _gi_cairo.cpython-310-x86_64-linux-gnu.so with build-id: a1854770e645829>
                                              Found module libpcre2-8.so.0 with build-id: 5117cabea71b00c1a5f5d696bfbc06fa1acf95d6
                                              Found module libblkid.so.1 with build-id: cdf95a964e3302bb356fefc4b801fae8c4340b31
                                              Found module libselinux.so.1 with build-id: 6fa53202ce676297de24873c886443b2759bfd8a
                                              Found module libmount.so.1 with build-id: eeb33f2b4b9c3eb0a29575eb9932ef08663bd836
                                              Found module libgio-2.0.so.0 with build-id: c3778bad9d8a3642cc51d453c07da246154dd4d7
                                              Found module libgmodule-2.0.so.0 with build-id: 65bf6e7985087f392ba1bc94b13a76f98eaaf>
                                              Found module libpcre.so.3 with build-id: 3982f316c887e3ad9598015fa5bae8557320476a
                                              Found module libffi.so.8 with build-id: 59c2a6b204f74f358ca7711d2dfd349d88711f6a
                                              Found module libgirepository-1.0.so.1 with build-id: 6f812440d4add17778e4134f2b1dd4c7>
                                              Found module libgobject-2.0.so.0 with build-id: 8a28a4aa6836963e7f50074984225cc07392b>
                                              Found module libglib-2.0.so.0 with build-id: 0ab0b740e34eeb0c84656ba53737f4c440dfbed4
                                              Found module _gi.cpython-310-x86_64-linux-gnu.so with build-id: 47e7f993303a321189a9b>
                                              Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265
                                              Found module _lzma.cpython-310-x86_64-linux-gnu.so with build-id: ae09e62d8cbdc2562b2>
                                              Found module libbz2.so.1.0 with build-id: e56b62c27bcc7ace8f9be36b255bd7b31bfde405
                                              Found module _bz2.cpython-310-x86_64-linux-gnu.so with build-id: bff0328dae5c2735ab3a>
                                              Found module ld-linux-x86-64.so.2 with build-id: 61ef896a699bb1c2e4e231642b2e1688b2f1>
                                              Found module libc.so.6 with build-id: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d
                                              Found module libz.so.1 with build-id: b22e9768303892af62d212ec9357a7f1a0824a91
                                              Found module libexpat.so.1 with build-id: 6311da0a7dd81c38b0470b6c535a8cc22d4443c2
                                              Found module libm.so.6 with build-id: 27e82301dba6c3f644404d504e1bb1c97894b433
                                              Found module python3.10 with build-id: 92425678868befe1e7e62cd5ae24b4bf701608a5
                                              Stack trace of thread 1884:
                                              #0  0x00007fc18cdfccf4 n/a (libgtk-3.so.0 + 0x18ccf4)
                                              #1  0x00007fc18ce14664 n/a (libgtk-3.so.0 + 0x1a4664)
                                              #2  0x00007fc18ce06754 n/a (libgtk-3.so.0 + 0x196754)
                                              #3  0x00007fc18e648ec3 g_type_create_instance (libgobject-2.0.so.0 + 0x3dec3)
                                              #4  0x00007fc18e62ff4d n/a (libgobject-2.0.so.0 + 0x24f4d)
                                              #5  0x00007fc18e6311ad g_object_new_with_properties (libgobject-2.0.so.0 + 0x261ad)
                                              #6  0x00007fc18e631cb1 g_object_new (libgobject-2.0.so.0 + 0x26cb1)
                                              #7  0x00007fc18d00d2d8 n/a (libgtk-3.so.0 + 0x39d2d8)
                                              #8  0x00007fc18e648ec3 g_type_create_instance (libgobject-2.0.so.0 + 0x3dec3)
                                              #9  0x00007fc18e62ff4d n/a (libgobject-2.0.so.0 + 0x24f4d)
                                              #10 0x00007fc18e6311ad g_object_new_with_properties (libgobject-2.0.so.0 + 0x261ad)
                                              #11 0x00007fc18e7dc4d0 n/a (_gi.cpython-310-x86_64-linux-gnu.so + 0x374d0)
                                              #12 0x0000560dd32f22ac _PyObject_MakeTpCall (python3.10 + 0x1522ac)
                                              #13 0x0000560dd32eac67 _PyEval_EvalFrameDefault (python3.10 + 0x14ac67)
                                              #14 0x0000560dd32fbfbc _PyFunction_Vectorcall (python3.10 + 0x15bfbc)
                                              #15 0x0000560dd32e45c9 _PyEval_EvalFrameDefault (python3.10 + 0x1445c9)
                                              #16 0x0000560dd32f1494 _PyObject_FastCallDictTstate (python3.10 + 0x151494)
                                              #17 0x0000560dd3305c04 n/a (python3.10 + 0x165c04)
                                              #18 0x0000560dd32f22ac _PyObject_MakeTpCall (python3.10 + 0x1522ac)
                                              #19 0x0000560dd32ea610 _PyEval_EvalFrameDefault (python3.10 + 0x14a610)
                                              #20 0x0000560dd32e0cc6 n/a (python3.10 + 0x140cc6)
                                              #21 0x0000560dd33d5eb6 PyEval_EvalCode (python3.10 + 0x235eb6)
                                              #22 0x0000560dd3403318 n/a (python3.10 + 0x263318)
                                              #23 0x0000560dd33fc03b n/a (python3.10 + 0x25c03b)
                                              #24 0x0000560dd3403065 n/a (python3.10 + 0x263065)
                                              #25 0x0000560dd3402548 _PyRun_SimpleFileObject (python3.10 + 0x262548)
                                              #26 0x0000560dd3402243 _PyRun_AnyFileObject (python3.10 + 0x262243)
                                              #27 0x0000560dd33f2b6e Py_RunMain (python3.10 + 0x252b6e)
                                              #28 0x0000560dd33c8e6d Py_BytesMain (python3.10 + 0x228e6d)
                                              #29 0x00007fc18f28ad90 __libc_start_call_main (libc.so.6 + 0x29d90)
                                              #30 0x00007fc18f28ae40 __libc_start_main_impl (libc.so.6 + 0x29e40)
                                              #31 0x0000560dd33c8d65 _start (python3.10 + 0x228d65)
                                              
                                              Stack trace of thread 1922:
                                              #0  0x00007fc18e6ab26d n/a (libglib-2.0.so.0 + 0x4026d)
                                              #1  0x00007fc18e6af333 g_hash_table_unref (libglib-2.0.so.0 + 0x44333)
                                              #2  0x00007fc18e4989fe n/a (libgio-2.0.so.0 + 0x10b9fe)
                                              #3  0x00007fc18e62ddfd g_object_unref (libgobject-2.0.so.0 + 0x22dfd)
                                              #4  0x00007fc18e49f7b0 n/a (libgio-2.0.so.0 + 0x1127b0)
                                              #5  0x00007fc18e49f977 g_dbus_connection_call_sync (libgio-2.0.so.0 + 0x112977)
                                              #6  0x00007fc18e4926b3 n/a (libgio-2.0.so.0 + 0x1056b3)
                                              #7  0x00007fc18e3d484c n/a (libgio-2.0.so.0 + 0x4784c)
                                              #8  0x00007fc18e43efc4 n/a (libgio-2.0.so.0 + 0xb1fc4)
                                              #9  0x00007fc18e6f26a4 n/a (libglib-2.0.so.0 + 0x876a4)
                                              #10 0x00007fc18e6efa41 n/a (libglib-2.0.so.0 + 0x84a41)
                                              #11 0x00007fc18f2f5b43 start_thread (libc.so.6 + 0x94b43)
                                              #12 0x00007fc18f387a00 __clone3 (libc.so.6 + 0x126a00)
                                              
                                              Stack trace of thread 1920:
                                              #0  0x00007fc18f379d7f __GI___poll (libc.so.6 + 0x118d7f)
                                              #1  0x00007fc18e715696 n/a (libglib-2.0.so.0 + 0xaa696)
                                              #2  0x00007fc18e6be3c3 g_main_context_iteration (libglib-2.0.so.0 + 0x533c3)
                                              #3  0x00007fc18e6be411 n/a (libglib-2.0.so.0 + 0x53411)
                                              #4  0x00007fc18e6efa41 n/a (libglib-2.0.so.0 + 0x84a41)
                                              #5  0x00007fc18f2f5b43 start_thread (libc.so.6 + 0x94b43)
                                              #6  0x00007fc18f387a00 __clone3 (libc.so.6 + 0x126a00)
                                              
                                              Stack trace of thread 1921:
                                              #0  0x00007fc18f37fa3d syscall (libc.so.6 + 0x11ea3d)
                                              #1  0x00007fc18e70f11c n/a (libglib-2.0.so.0 + 0xa411c)
                                              #2  0x00007fc18e492069 n/a (libgio-2.0.so.0 + 0x105069)
                                              #3  0x00007fc18e3d484c n/a (libgio-2.0.so.0 + 0x4784c)
                                              #4  0x00007fc18e43efc4 n/a (libgio-2.0.so.0 + 0xb1fc4)
                                              #5  0x00007fc18e6f26a4 n/a (libglib-2.0.so.0 + 0x876a4)
                                              #6  0x00007fc18e6efa41 n/a (libglib-2.0.so.0 + 0x84a41)
                                              #7  0x00007fc18f2f5b43 start_thread (libc.so.6 + 0x94b43)
                                              #8  0x00007fc18f387a00 __clone3 (libc.so.6 + 0x126a00)
                                              
                                              Stack trace of thread 1924:
                                              #0  0x00007fc18f305930 _int_malloc (libc.so.6 + 0xa4930)
                                              #1  0x00007fc18f305dcf _int_memalign (libc.so.6 + 0xa4dcf)
                                              #2  0x00007fc18f308206 _mid_memalign (libc.so.6 + 0xa7206)
                                              #3  0x00007fc18e6df8b7 n/a (libglib-2.0.so.0 + 0x748b7)
                                              #4  0x00007fc18e6e1166 g_slice_alloc (libglib-2.0.so.0 + 0x76166)
                                              #5  0x00007fc18e6ffe05 g_variant_new_dict_entry (libglib-2.0.so.0 + 0x94e05)
                                              #6  0x00007fc18e4d096b n/a (libgio-2.0.so.0 + 0x14396b)
                                              #7  0x00007fc18e4d0f22 n/a (libgio-2.0.so.0 + 0x143f22)
                                              #8  0x00007fc18e49b89c g_dbus_message_new_from_blob (libgio-2.0.so.0 + 0x10e89c)
                                              #9  0x00007fc18e4a9b85 n/a (libgio-2.0.so.0 + 0x11cb85)
                                              #10 0x00007fc18e43ec89 n/a (libgio-2.0.so.0 + 0xb1c89)
                                              #11 0x00007fc18e43eccd n/a (libgio-2.0.so.0 + 0xb1ccd)
                                              #12 0x00007fc18e6c0c24 g_main_context_dispatch (libglib-2.0.so.0 + 0x55c24)
                                              #13 0x00007fc18e7156f8 n/a (libglib-2.0.so.0 + 0xaa6f8)
                                              #14 0x00007fc18e6c0293 g_main_loop_run (libglib-2.0.so.0 + 0x55293)
                                              #15 0x00007fc18e4a1c1a n/a (libgio-2.0.so.0 + 0x114c1a)
                                              #16 0x00007fc18e6efa41 n/a (libglib-2.0.so.0 + 0x84a41)
                                              #17 0x00007fc18f2f5b43 start_thread (libc.so.6 + 0x94b43)
                                              #18 0x00007fc18f387a00 __clone3 (libc.so.6 + 0x126a00)
Aug 24 10:39:57 i3793 systemd[1873]: startExpressVpn_Monitor.service: Main process exited, code=dumped, status=11/SEGV
Aug 24 10:39:57 i3793 systemd[1873]: startExpressVpn_Monitor.service: Failed with result 'core-dump'.
lines 148-189/189 (END)

Manually running systemctl --user start startExpressVpn_Monitor.service, works without error.

**Comment by MaherGebrail** [comment]
@chasbro-1

**install.sh** file copies **ExpressVpn_Monitor.desktop** file  into **/home/$user_name/.config/autostart/** dir to prevent errors from the app before the os-gui get fully loaded.

Many errors may occurs if a gui-app started before the os-gui starts .. so to enable the service without errors you have to make it starts after the session manager loads.

Since the app made to be flexible with different session-managers .. the app mainly depends upon the **autostart** file more than enabling the service.

**Comment by MaherGebrail** [comment]
@chasbro-1 

If you want to enable the service without The *.Desktop file, You may now uncomment the last line in **common_functions.py** file before installing and make sure that the env session var in your system is the same as the func args .. 

_The Function wil check the display before letting the app run._
